[advisories]
db-path = "https://github.com/rustsec/advisory-db"
severity-threshold = "medium"
ignore = []

[bans]
multiple-versions = "warn"
deny = []

[licenses]
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MIT-0",
    "MPL-2.0",
    "Unlicense",
    "Zlib",
    "Unicode-DFS-2016",
]
deny = [
    "GPL-1.0",
    "GPL-1.0+",
    "GPL-2.0",
    "GPL-2.0+",
    "GPL-3.0",
    "GPL-3.0+",
    "LGPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
]
exception = []

[[licenses.clarify]]
name = "ring"
license = "BSD-3-Clause"
expression = "ISC AND MIT AND OpenSSL"

[[licenses.clarify]]
name = "webpki"
license = "BSD-3-Clause"
expression = "BSD-3-Clause"

[future-incompat]
denied = true

[sources]
unknown-registry = "deny"
unknown-git = "deny"
